MajorsPool/Controllers/PickController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;
using SendGridMail;
using SendGridMail.Transport;
//using SharedServiceInterface;
using MajorsPool.Models;
//using MajorsPoolEmailService;
using System.ServiceModel;

namespace MajorsPool.Controllers
{
    public class PickController : Controller
    {
        private MajorsPoolDb db = new MajorsPoolDb();
        private const int HOURS_TO_PICK = 12;        
        private const string EMPTY = "";
       
        //
        // GET: /Pick/
        
        public ActionResult Index(int Admin = 0, string Password = EMPTY)
        {
            string xxx = string.Empty;

            try
            {
                xxx += "1";
                Session["Admin"] = (Convert.ToBoolean(Session["Admin"]) == true || Admin == 318) ? true : false;
                xxx += "1";
                ViewBag.UserVerified = VerifyUser(Password);
                xxx += "1";
                UpdateExpiredUsers();
                xxx += "1";
                UpdatePickEligibles();
                xxx += "1";
                // Test reference to http://localhost:58249/PickNotificationService.svc
                //ServiceReference1.PickNotificationServiceClient clientRef = new ServiceReference1.PickNotificationServiceClient();
                //ViewBag.Blah = clientRef.SendEmail(5, "X");
                //MajorsPoolServiceReference.PickNotificationServiceClient serviceRef = new MajorsPoolServiceReference.PickNotificationServiceClient();
                //string response = serviceRef.SendEmail(3, "5");
                //ViewBag.Blah = response;

                //MajorsPoolCloudServiceReference.PickNotificationServiceClient serviceRef = new MajorsPoolCloudServiceReference.PickNotificationServiceClient();
                //string response = serviceRef.SendEmail(4, "5");
                //ViewBag.Blah = response;

                return View(from p in db.Picks
                            orderby p.SeqNo
                            select p);
            }
            catch (Exception ex)
            {
                ViewBag.Blah = ex.Message + xxx + db.Database.Connection.ConnectionString + "end"; //ex.Message;
                return View();
            }
        }

        private bool VerifyUser(string password)
        {
            return true;
        }

        private string UpdateExpiredUsers()
        {
            Pick lastPersonToPick;
            Pick checkForExpirationPick;

            string returnString;

            try
            {

                do
                {
                    lastPersonToPick = (from p in db.Picks.AsEnumerable() where p.PickTime != null orderby p.SeqNo select p).LastOrDefault();

                    checkForExpirationPick = null;

                    if (lastPersonToPick != null)
                    {
                        if (lastPersonToPick.PickTime != null) // Shouldn't this always be true?
                        {
                            // If it's been more than 12 hours since the most recent pick.
                            if (new TimeSpan(DateTime.Now.Ticks - Convert.ToDateTime(lastPersonToPick.PickTime).Ticks).TotalHours > HOURS_TO_PICK)
                            {
                                // Get the pick that is next up.
                                checkForExpirationPick = (from p in db.Picks.AsEnumerable() where p.PickTime == null orderby p.SeqNo select p).FirstOrDefault();

                                if (checkForExpirationPick != null)
                                {
                                    // Assign a pick time, even though there is no golfer associated with the pick.
                                    checkForExpirationPick.PickTime = Convert.ToDateTime(lastPersonToPick.PickTime).AddHours(HOURS_TO_PICK);

                                    db.Entry(checkForExpirationPick).State = EntityState.Modified;

                                    db.SaveChanges();

                                    SendNextEmailNotification();
                                }
                            }
                        }
                    }
                } while (checkForExpirationPick != null);
            }
            catch (Exception ex)
            {
                returnString = ex.Message;
            }

            return "good";
        }

        private void UpdatePickEligibles()
        {
            int nextUpUsersPickId;

            try
            {
                nextUpUsersPickId = (from x in db.Picks.AsEnumerable() where x.PickTime == null orderby x.SeqNo select x.PickId).FirstOrDefault();
                
                foreach (var pick in db.Picks.AsEnumerable())
                {
                    // Entrant hasn't picked, and is next in line...OR
                    // Entrant hasn't picked, but he has been assigned a picktime (implying that his time has expired)
                    pick.PickEligible = ((pick.GolferId == null && pick.PickId == nextUpUsersPickId) ||
                                         (pick.GolferId == null && pick.PickTime != null));

                    db.Entry(pick).State = EntityState.Modified;
                }

                db.SaveChanges();
            }
            catch (Exception)
            {
                //nextUpUsersPickId = -1;
            }
        }

        //
        // GET: /Pick/Details/5
        
        public ActionResult Details(int id = 0)
        {
            Pick pick = db.Picks.Find(id);
            
            if (pick == null)
            {
                return HttpNotFound();
            }

            GolferController hc = new GolferController();

            pick.Golfer = hc.GetGolfer(pick.Golfer.GolferId);

            return View(pick);
        }

        //
        // GET: /Pick/Create
        
        public ActionResult Create()
        {
            EntrantController ec = new EntrantController();
            GolferController gc = new GolferController();
            
            ViewBag.EntrantList = ec.GetEntrants();
            ViewBag.GolferList = gc.GetGolfers();

            return View();
        }

        //
        // POST: /Pick/Create

        [HttpPost]
        public ActionResult Create(Pick pick)
        {
            if (ModelState.IsValid)
            {
                pick.Entrant = db.Entrants.Find(pick.Entrant.EntrantId);

                db.Picks.Add(pick);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        private void ConstructAndSendEmail(string emailTo, /*int pickId,*/ int entrantId)
        {
            var from = new MailAddress("noreply@majorspool.com");
            var to = new MailAddress[] { new MailAddress(emailTo) };
            var cc = new MailAddress[] { };
            var bcc = new MailAddress[] { new MailAddress("scott.m.manny@gmail.com") };
            var subject = "Majors Pool - Your Turn";

            EntrantController ec = new EntrantController();            
            
            var securityCode = ec.GetEntrant(entrantId).SecurityCode;

            var expirationTime = DateTime.Now.AddHours(HOURS_TO_PICK);
            
            expirationTime = DateTime.SpecifyKind(expirationTime, DateTimeKind.Utc);

            // Convert UTC time to central.
            TimeZoneInfo cstZone = TimeZoneInfo.FindSystemTimeZoneById("Central Standard Time");

            DateTime cstTime = TimeZoneInfo.ConvertTimeFromUtc(expirationTime, cstZone);

            var html = 
                    "<body style=\"font-family: Calibri\">" +
                    "    <div style=\"font-size: 16pt; color: darkgreen\">" +
                    "        Majors Pool" + 
                    "    </div>" + 
                    "    <div style=\"color: #333333; font-size: 12pt\">" +
                    "        <span>" +
                    "            Hi " + ec.GetEntrant(entrantId).FirstName + "," +
                    "            <br/>" +
                    "            <br/>" +
                    "            Your security code is <b>" + securityCode + "</b>.  You will need this to make your pick." +
                    "        </span>" +
                    "        <br />" +
                    "        <br />" + 
                    "        <span>" +
                    "            You have until <b>" + cstTime.ToShortDateString() + " " + cstTime.ToShortTimeString() + "</b> to make your pick from the following link:  <a href=\"http://majorspool.azurewebsites.net/Pick\">Majors Pool Draft</a>" +
                    "        </span>" + 
                    "        <br />" + 
                    "        <br />" + 
                    "        <div style=\"font-size: 12pt; color: darkgreen\">" + 
                    "            <b>Consequences</b>" + 
                    "            <br />" + 
                    "            <span style=\"color: #333333\">" + 
                    "                If your time expires, the draft selection will become unblocked allowing " + 
                    "                the next person in line to make their selection.  You will still be able to make your pick at anytime, but keep in mind that the longer you wait, the fewer golfers will be available." +
                    "            </span>" + 
                    "        </div>" + 
                    "    </div>" + 
                    "</body>";
            
            var text = "You have until " + cstTime.ToShortDateString() + " " + cstTime.ToShortTimeString() + " to make your pick from the following link:  http://majorspool.azurewebsites.net/Pick\">Majors Pool Draft</a>";

            SendGrid pickNotification = SendGrid.GetInstance(from, to, cc, bcc, subject, html, text);

            var username = "azure_dcc2b608e977cca58a411ed82cbe6da3@azure.com";

MajorsPool/Views/Shared/_Layout.cshtml
<!doctype html>
 
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>@ViewBag.Title - Majors Pool</title>
    @*<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.0/themes/base/jquery-ui.css" />*@
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")

        @Scripts.Render("~/bundles/jqueryTimer")
        
        @Scripts.Render("~/bundles/modernizr")
  <link rel="stylesheet" href="/resources/demos/style.css" />
  <style>
    label, input { display:block; }
    input.text { margin-bottom:12px; width:95%; padding: .4em; }
    fieldset { padding:0; border:0; margin-top:25px; }
    h1 { font-size: 1.2em; margin: .6em 0; }
    div#users-contain { width: 350px; margin: 20px 0; }
    div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
    div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
    .ui-dialog .ui-state-error { padding: .3em; }
    .validateTips { border: 1px solid transparent; padding: 0.3em; }
  </style>
    </head>
    <body>
        <header>

            <div class="content-wrapper" style="padding-left: 14px">
                
                <table class="float-left" style="border-width: 1px; border-style: none; width: 100%" border="1">
                    <tr>
                        <td class="tdLogo" style="border-width: 1px; border-style: none; text-align: center">
                            <img id="logo" class="logo" src="~/Images/blue.png" />
                            @*<div id="logo" style="background-color: transparent">&nbsp;&nbsp;&nbsp;</div>*@
                        </td>
                        <td class="tdTitle" style="border-width: 1px; border-style: none;">
                            <span class="site-title" style="vertical-align: middle">@Html.ActionLink("PGA Championship", "Index", "Pick")</span>
                        </td>
                        <td class="tdMenu" >
                            <nav>
                                <ul id="menu">
                                    @if (Convert.ToBoolean(Session["Admin"]))
                                    {
                                        <li>@Html.ActionLink("Home", "Index", "Pick")</li>
                                        <li>@Html.ActionLink("Golfer", "Index", "Golfer")</li>
                                        <li>@Html.ActionLink("Entrant", "Index", "Entrant")</li>
                                        <li>@Html.ActionLink("TopPickList", "Index", "TopPickList")</li>
                                    }
                                    <li><a href="~/Documents/Majors Pool.pdf">Rules</a>
                                </ul>
                            </nav>
                        </td>
                    </tr>
                </table>
                
            </div>

        </header>

        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        
        

        @Scripts.Render("~/bundles/secretAdmin")        
        
        @RenderSection("scripts", required: false)

        </body>
    </html>